version: "3.9"
services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    restart: unless-stopped
    ports:
      - "22:2222"                # host 22 → container 2222 (honeypot)
    volumes:
      - ../cowrie/etc:/cowrie/cowrie-git/etc
      - ../cowrie/var:/cowrie/cowrie-git/var
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
